config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/about' => 'static_pages#about'

  resources :posts

  resources :authors do
    resources :posts, only: [:index]
  end

end

app/models/ad.rb
class Ad

  attr_accessor :id, :pic, :url, :headline, :text, :title

  def initialize(args)
    self.title      = args[:title]
    self.id         = args[:id]
    self.pic        = args[:pic]
    self.url        = args[:url]
    self.headline   = args[:headline]
    self.text       = args[:text]
  end

  def self.all
    unless defined?(@ads)
      @ads = [
        Ad.new(
          id: 1,
          title: 'Butter is Delish',
          pic: 'butter',
          url: 'http://www.butter.com',
          headline: 'BUTTER WILL MAKE EVERYONE LIKE YOU',
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        ),
        Ad.new(
          id: 2,
          title: 'Gillette Razors',
          pic: 'gillette',
          url: 'http://www.gillette.com',
          headline: 'IT IS UNLIKELY YOUR BABY WILL SHAVE ITS FACE OFF',
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        ),
        Ad.new(
          id: 3,
          title: 'Old Spice smells Great',
          pic: 'old-spice',
          url: 'http://www.oldspice.com',
          headline: 'OLD SPICE IS BETTER THAN A LOBOTOMY',
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        ),
        Ad.new(
          id: 4,
          title: 'Join the Dark Side',
          pic: 'starwars',
          url: 'http://www.starwars.com',
          headline: "JOIN THE DARK SIDE. IT'S NICE.",
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        ),
        Ad.new(
          id: 5,
          title: 'Vitameatavegamin - For Your Health',
          pic: 'vitameatavegamin',
          url: 'https://www.youtube.com/watch?v=4AZK2-Tfc84',
          headline: 'ARE YOU RUN DOWN AND LISTLESS?',
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        ),
        Ad.new(
          id: 6,
          title: 'Youtube',
          pic: 'youtube',
          url: 'http://www.youtube.com',
          headline: 'DIGITAL IS FOREVER',
          text: %q(
            Keffiyeh austin four dollar toast food truck banjo, echo park readymade. Wolf blue bottle hoodie tacos. Organic fanny pack tofu sriracha, kombucha vice small batch actually williamsburg deep v. Pour-over green juice fanny pack chambray. Dreamcatcher raw denim green juice, seitan mumblecore pork belly pinterest flannel 3 wolf moon banjo yuccie. Swag letterpress hashtag, man braid flannel heirloom trust fund kale chips. Pabst ugh DIY keffiyeh, iPhone artisan man bun migas taxidermy wayfarers.
          )
        )
      ]
    end
    @ads
  end

end

app/models/author.rb
class Author < ActiveRecord::Base

  has_many :posts

  validates :name, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :author

  validates :title, :body, :author, presence: true
  validate :title_long_enough

  def first_half(text)
    paragraph_array = text.split("\n")
    first_half = paragraph_array.slice(0..paragraph_array.length/2 - 1)
    first_half.join("\n")
  end

  def second_half(text)
    paragraph_array = text.split("\n")
    second_half = paragraph_array.slice(paragraph_array.length/2..-1)
    second_half.join("\n")
  end

  def title_long_enough
    errors.add(:title, " is #{10-title.length} characters too short") if title.length < 10
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :get_ad

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  private

  def get_ad
    @ad = Ad.all.sample
  end

  def author_params
    params.require(:author).permit(:name)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :get_posts, only: [:index, :show]
  before_action :fetch_post, only: [:show, :edit, :update, :destroy]
  before_action :get_ad
  before_action :get_recent_posts, only: [:index, :show]

  def index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'new'
    end
  end

  private

  def get_posts
    if params[:author_id]
      @posts = Post.where("author_id = ?", params[:author_id]).order("created_at DESC").page(params[:page]).per_page(10)
    else
      @posts = Post.order("created_at DESC").page(params[:page]).per_page(10)
    end
  end

  def fetch_post
    @post = Post.find(params[:id])
  end

  def get_ad
    @ad = Ad.all.sample
  end

  def get_recent_posts
    @recent_posts = get_posts.where("id != ?", params[:id]).limit(4)
  end

  def post_params
    params.require(:post).permit(:title, :body, :thumbnail, :interject, :author_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
    @title = "About"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/authors/_form.html.erb
<%= form_for author, html: { class: "form" } do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prevented this author from being saved:</h2>
      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="">
    <%= f.submit (author.persisted? ? "Save Author" : "Create Author"), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 post-form">
      <h1>EDIT AUTHOR</h1>

      <%= render partial: "form", locals: { author: @author } %>

      <div id="home-link">
        <%= link_to "Back to Home", root_path %>
      </div>
    </div>
    <div class="col-sm-4">
      <aside>
        <%= render partial: '/posts/ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>

app/views/authors/new.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 post-form">
      <h1>CREATE NEW AUTHOR</h1>

      <%= render partial: "form", locals: { author: @author } %>

      <div id="home-link">
        <%= link_to "Back to Home", root_path %>
      </div>
    </div>
    <div class="col-sm-4">
      <aside>
        <%= render partial: '/posts/ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    <%= @current_post ? @current_post.title : @title %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</head>
<body>
  <header>
    <div class="container">
      <div class="row">
        <div class="col-xs-6 logo">
          <%= link_to image_tag('logo', id: 'logo')+"THE AUTHORITARIAN BLOG", root_path %>
        </div>
        <div class="col-xs-6">
          <nav>
            <ul class="list-inline text-right">
              <li><%= link_to "ABOUT", '/about' %></li>
              <li><a href="#">SEARCH <i class="glyphicon glyphicon-search"></i></a></li>
            </ul>
          </nav>
        </div>
      </div>
      <h1 class="text-center">THE AUTHORITARIAN</h1>
      <h2 class="text-center">Great Authors. Great Content.</h2>
    </div>
  </header>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          The Ironyard Copyright 2013. All Rights Reserved
        </div>
        <div class="col-xs-6">
          <nav>
            <ul class="list-inline text-right">
              <li><a href="#">Books</a></li>
              <li><a href="#">Are</a></li>
              <li><a href="#">Neat</a></li>
              <li><a href="#">Read</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </footer>
<script 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</body>
</html>

app/views/posts/_ad.html.erb
<div class="ad">
  <%= link_to(ad.url) do %>
    <%= image_tag(ad.pic, class: "img-responsive") %>
    <%= content_tag(:h6, ad.title, class: "text-right") %>
  <% end %>
  <h2><%= @ad.headline %></h2>
  <p><%= @ad.text %></p>
</div>

app/views/posts/_form.html.erb
<%= form_for post, html: { class: "form" } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prevented this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: '15' %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.select('author_id', Author.all.map { |auth| [ auth.name, auth.id ] }, {include_blank: 'None'}, class: 'form-control') %>
  </div>
  <div class="">
    <%= f.submit (post.persisted? ? "Save Post" : "Create Post"), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/_post_links.html.erb
<div class="container-fluid post-links">
  <div class="row">
    <div class="col-xs-12 headline text-center">
      <h1>MOST RECENT POSTS</h1>
    </div>
    <% @recent_posts.each do |post| %>
      <% unless post.id == @post.id %>
        <div class="col-xs-3 post-link">
          <%= link_to(post_path(post)) do %>
            <%= image_tag(post.thumbnail, class: 'img-responsive') %>
            <%= content_tag(:h2, post.title) %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 post-form">
      <h1>EDIT POST</h1>

      <%= render partial: "form", locals: { post: @post } %>

      <div id="home-link">
        <%= link_to "Back to Posts", root_path %>
      </div>
    </div>
    <div class="col-sm-4">
      <aside>
        <%= render partial: 'ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 content">
      <main>
        <h1>ALL POSTS</h1>
        <% @posts.each do |post| %>
          <div class="post-link">
            <%= link_to post.title, post_path(post) %>
            <h5>By <%= post.author.name %> on <%= post.created_at.strftime("%A %b %d %Y %-I:%M %p") %></h5>
          </div>
        <% end %>
        <div class="options">
          <%= link_to new_post_path do %>
          <i class="glyphicon glyphicon-comment"></i>New Post
          <% end %>
          <%= link_to new_author_path do %>
          <i class="glyphicon glyphicon-cloud-upload"></i>New Author
          <% end %>
        </div>
        <%= will_paginate @posts %>

      </main>
    </div>
    <div class="col-sm-4">
      <aside>
        <%= render partial: 'ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 post-form">
      <h1>CREATE NEW POST</h1>

      <%= render partial: "form", locals: { post: @post } %>

      <div id="home-link">
        <%= link_to "Back to Posts", root_path %>
      </div>
    </div>
    <div class="col-sm-4">
      <aside>
        <%= render partial: 'ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container content">
  <div class="row">
    <div class="col-sm-8 content">
      <main>
        <h1><%= @post.title.upcase %></h1>
        <div class="subheading">
          <%= image_tag(@post.author.picture, class: 'avatar') %>
          <p><%= @post.author.name %> <span>on <%= @post.created_at.strftime("%A %b %d %Y %-I:%M %p") %></span></p>
        </div>
        <%= simple_format @post.first_half(@post.body) %>
        <% if @post.interject %>
          <div class="interject">
            <%= @post.interject %>
          </div>
        <% end %>
        <%= simple_format @post.second_half(@post.body) %>
        <div class="options">
          <a href="#"><i class="glyphicon glyphicon-comment"></i>Read Comments</a>
          <%= link_to author_posts_path(@post.author) do %>
          <i class="glyphicon glyphicon-cloud-upload"></i>Author's Posts
          <% end %>
          <%= link_to edit_post_path(@post) do %>
          <i id="share" class="glyphicon glyphicon-share"></i>Edit This Post
          <% end %>
        </div>

      </main>
    </div>
    <div class="col-sm-4">
      <aside>
        <div class="author">
          <%= image_tag(@post.author.picture, class: 'avatar') %>
          <h3 class="text-center"><%= @post.author.name.upcase %></h3>
          <ul class="list-inline text-center">
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Instagram</a></li>
          </ul>
        </div>
        <%= render partial: 'ad', locals: { ad: @ad } %>
      </aside>
    </div>
  </div>
</div>
<%= render partial: "post_links" %>

app/views/static_pages/about.html.erb
<div class="container about">
  <div class="row">
    <div class="col-xs-12">
      <h1>About The Authoritarian</h1>
      <p>
        Beard twee scenester actually, shoreditch man bun gastropub wolf. Narwhal squid you probably haven't heard of them readymade ennui, tofu banjo food truck. Leggings pitchfork brooklyn, truffaut organic wayfarers twee tumblr. Next level hashtag blog, readymade twee actually vice. Single-origin coffee pinterest bespoke, green juice microdosing waistcoat typewriter vinyl +1 PBR&B beard. Listicle twee thundercats vice echo park. Cronut listicle craft beer, banh mi cliche pickled farm-to-table trust fund swag vice vegan fap gastropub scenester actually.
      </p>
      <p>
        Fashion axe authentic biodiesel seitan etsy mixtape cronut affogato banh mi four dollar toast franzen. Cronut sriracha YOLO, pop-up man bun knausgaard kombucha fixie humblebrag biodiesel. Bespoke cred offal polaroid blue bottle, next level you probably haven't heard of them. Hella portland readymade retro, salvia raw denim squid asymmetrical brooklyn flexitarian tousled YOLO taxidermy. 90's narwhal man bun chambray, ugh trust fund slow-carb ennui microdosing put a bird on it church-key mustache messenger bag. Authentic PBR&B art party health goth, mlkshk actually umami flannel blue bottle blog. Fashion axe fixie squid, before they sold out master cleanse truffaut ennui leggings next level try-hard.
      </p>
      <p>
        Portland iPhone gentrify, sriracha swag narwhal viral before they sold out pabst hoodie salvia small batch squid truffaut waistcoat. Wayfarers slow-carb shabby chic, pitchfork venmo meditation cardigan health goth sriracha cornhole twee organic selvage godard artisan. Roof party chillwave you probably haven't heard of them biodiesel, vice typewriter franzen truffaut whatever vegan 3 wolf moon trust fund plaid cray authentic. Deep v sartorial four loko, cold-pressed health goth chillwave mumblecore ennui brooklyn twee XOXO letterpress. Listicle master cleanse cred poutine cliche. 3 wolf moon retro waistcoat seitan truffaut readymade chia. Franzen hella humblebrag, bitters listicle organic post-ironic chicharrones man braid kale chips.
      </p>
      <%= link_to 'Back to Home', root_path %>
    </div>
  </div>
</div>